// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package doakeswire

import (
	"github.com/domesama/doakes/server"
)

// Injectors from wire.go:

// InitializeTelemetryServer creates a fully configured internal telemetry server using Wire.
// The server is created but NOT started. You must call Start() yourself.
func InitializeTelemetryServer() (*server.TelemetryServer, error) {
	resource, err := ProvideResource()
	if err != nil {
		return nil, err
	}
	metricsConfig := ProvideMetricsConfig()
	telemetryServerConfig, err := ProvideTelemetryServerConfig()
	if err != nil {
		return nil, err
	}
	options := ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, err := server.New(options)
	if err != nil {
		return nil, err
	}
	return telemetryServer, nil
}

// InitializeTelemetryServerWithAutoStart creates and starts a internal telemetry server using Wire.
// Returns the server, a cleanup function, and an error.
// The server is started but health checks are NOT enabled - call EnableHealthCheck() after setup.
//
// Usage:
//
//	srv, cleanup, err := wire.InitializeTelemetryServerWithAutoStart()
//	if err != nil {
//	    return err
//	}
//	defer cleanup()
//
//	srv.RegisterHealthCheck("database", checkDB)
//	srv.EnableHealthCheck()
func InitializeTelemetryServerWithAutoStart() (*server.TelemetryServer, func(), error) {
	resource, err := ProvideResource()
	if err != nil {
		return nil, nil, err
	}
	metricsConfig := ProvideMetricsConfig()
	telemetryServerConfig, err := ProvideTelemetryServerConfig()
	if err != nil {
		return nil, nil, err
	}
	options := ProvideServerOptions(resource, metricsConfig, telemetryServerConfig)
	telemetryServer, cleanup, err := ProvideServer(options)
	if err != nil {
		return nil, nil, err
	}
	return telemetryServer, func() {
		cleanup()
	}, nil
}
